### ISSUE TITLE
Redesign website

### ISSUE THREAD

**Issue by felipeferreirah** [audacity/audacity.github.io#29]
Hey everyone, did you see the redesign of the [Link Audacity](https://dribbble.com/shots/20768853-audacity-web-design) site?
I was thinking of opening a pull request with this layout implemented. What do you guys think?

Print:
![image](https://github.com/user-attachments/assets/8649628f-870c-488d-b435-78b493dd4803)

**Comment by LWinterberg** [comment]
Unfortunately Audacity isn't quite there yet to take advantage of this design - we don't have a goniometer for one, and the waveform doesn't look like what you're showing here either. Logo, too, is different. 

It also misses the most important point of the website: The download button. It's super tucked away with the visually interesting stuff happening on the other side of the screen.
