### ISSUE TITLE
replace ugly linebreak in hero with `text-wrap: balance` or `pretty`

### ISSUE THREAD

**Issue by LWinterberg** [audacity/audacity.github.io#7]
it got into ff 11 days ago, so we probably should wait for a bit with that though. 

https://bugzilla.mozilla.org/show_bug.cgi?id=1731541
https://developer.mozilla.org/en-US/docs/Web/CSS/text-wrap#browser_compatibility
https://caniuse.com/css-text-wrap-balance

**Comment by DilsonsPickles** [comment]
Fixed here using max-width on text div: https://github.com/audacity/audacity.github.io/actions/runs/6529478123
